In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3, 5) # reshape操作

In [5]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [6]:
x.ndim # ndim -> 向量或矩阵的维度

1

In [7]:
X.ndim

2

In [8]:
x.shape # shape -> 返回一个元组

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size # size -> 元素个数

10

In [11]:
X.size

15

## numpy.array 的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1]

9

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[0][0] #不推荐

0

In [17]:
X[(2, 2)]

12

In [18]:
X[2, 2] #numpy中推荐使用这种方式访问矩阵

12

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
 x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
X[:2, :3] #访问矩阵的前2行前3列

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
X[:2][:3] #不能满足需求

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
X[0, :]

array([0, 1, 2, 3, 4])

In [30]:
X[:, 0]

array([ 0,  5, 10])

In [31]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
subX[0][0] = 100 #subX是原矩阵X的引用，修改会导致X也被修改
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [34]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [35]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX = X[:2, :3].copy() #创建一个X的拷贝，修改subX，不影响X
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [39]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape

In [40]:
x.shape

(10,)

In [41]:
x.reshape(2, 5) #未改变x，返回一个新的reshape后的矩阵

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
 B = x.reshape(1, 10)

In [45]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
B.ndim

2

In [47]:
x.reshape(10, -1) #reshape成10行，列数自动计算

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 合并操作

In [48]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [49]:
x

array([1, 2, 3])

In [50]:
y

array([3, 2, 1])

In [51]:
np.concatenate([x, y]) #拼接2个向量，只能处理维度相同的向量或矩阵

array([1, 2, 3, 3, 2, 1])

In [52]:
z = np.array([4, 5, 6])

In [53]:
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 4, 5, 6])

In [54]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [55]:
np.concatenate([A, A]) #默认沿行的方向拼接

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
np.concatenate([A, A], axis=1) #axis=1指定沿列的方向

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
np.concatenate([A, z.reshape(1, -1)])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [59]:
np.vstack([A, z]) #维度不同拼接

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [60]:
B = np.full((2, 2), 100)

In [61]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割操作

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.split(x, [3, 7]) #第二个参数指定分割点，可以有多个

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [64]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [65]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [68]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
np.hsplit(A, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [70]:
data = np.arange(16).reshape((4, 4)) #假设前3列为特征，最后一列为标签
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
X, y = np.split()