# numpy.array基础

In [64]:
import numpy as np

In [65]:
np.__version__

'1.23.5'

## python List 的特点

1. List存储的类型可以不一样，比较灵活，但是效率相对比较低。
2. array只能存储相同类型的元素。效率比List高，但是没有向量或矩阵的运算。

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L[5]

5

In [9]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [10]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [11]:
 import array

In [12]:
arr = array.array('i', [i for i in range(10)]) #'i'表示存储的元素类型为整形
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [14]:
arr[5] = 100

In [15]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [16]:
arr[5] = 'Marchine Learning'

TypeError: 'str' object cannot be interpreted as an integer

## numpy.array

In [17]:
nparr = np.array([i for i in range(10)]) #使用np.array()传入一个List创建
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[5]

5

In [20]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [21]:
 nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [23]:
nparr.dtype #查看 numpy.array 中存储的元素类型

dtype('int64')

In [24]:
nparr[5] = 5.0 #进行了隐式转换

In [25]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
nparr.dtype

dtype('int64')

In [27]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
nparr.dtype

dtype('int64')

In [29]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

In [30]:
np.zeros(10) #创建一个零数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10).dtype

dtype('float64')

In [32]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros((3, 5)) #传入一个元组，创建一个二维矩阵: 3行5列

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
 np.ones(10) #创建一个全1的向量或矩阵

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.full(shape=(3, 5), fill_value=666) #创建一个指定值的向量或矩阵

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [39]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange

In [40]:
[i for i in range(0, 20, 2)] #起始点，终止点(不包含)，步长(默认为1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [41]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

### linspace

In [44]:
np.linspace(0, 20, 10 ) #在[0, 20]区间内截出等长的10个点

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [45]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [46]:
np.random.randint(0, 10) #生成一个[0, 10)之间的随机数

7

In [47]:
np.random.randint(0, 10, 10) #生成一个10个元素的向量，每个元素在[0, 10）

array([7, 4, 9, 7, 5, 7, 7, 7, 0, 5])

In [48]:
np.random.randint(4, 8, size=10) #生成一个大小为10，取值在[4, 8)之间的随机数组

array([6, 7, 5, 6, 5, 5, 4, 4, 5, 4])

In [49]:
np.random.randint(4, 8, size=(3, 5))

array([[6, 6, 7, 5, 7],
       [6, 7, 7, 6, 5],
       [6, 7, 6, 4, 4]])

In [50]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 7, 5, 4],
       [4, 7, 6, 4, 5],
       [6, 6, 4, 7, 6]])

In [51]:
np.random.seed(666)

In [52]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [53]:
np.random.seed(666) #使用相同的随机数种子，前后2次生成的随机矩阵相同

In [54]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [55]:
np.random.random() #默认生成一个[0, 1)内浮点数类型的随机数。在[0,1)之间均匀分布

0.2811684913927954

In [56]:
np.random.random(10) #参数默认为size

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [57]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [58]:
np.random.normal() #[0,1)之间符合正态分布的随机数。均值为0，方差为1

0.7760516793129695

In [59]:
np.random.normal(10, 100) #均值为10，方差为100

128.06359754812632

In [60]:
np.random.normal(0, 1, size=(3, 5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

## 查看文档

In [61]:
np.random.normal?

In [62]:
np.random?

In [63]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution