# 测试我们的模型

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape #150个训练样本，每个训练样本有4个特征

(150, 4)

In [5]:
y.shape #每个训练样本的标签

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X)) #对索引进行随机排列

In [8]:
shuffle_indexes

array([ 58,  70,  48, 106,  52,  62,   5,  51,  87, 107,  53,  40, 128,
        35,  76, 103, 105,  34, 123,  11, 145, 109,  14,  47, 149,  92,
        90,  31, 114,  84, 117, 129, 112, 125,  67,  10,  97,  21, 146,
        82, 108,  30,  55, 126, 110,  65,  81,  16, 131,  50,  88, 104,
        95,  27, 135,  57, 119,  44, 136, 147,  17, 116,  74,  61,  71,
         2,  38,  63,  26,  23,  66, 140, 142,  99,  45, 100,  29,  42,
       132, 111, 102,  85,  12, 118,   7,  46,  83, 134,  43,  64,  77,
        54, 133,  25,  28,  69,  18,   8,  86,  22,  20, 148,  13,  33,
       120, 124,  15,   3,  19, 122,  75,   9,  78,  32,  96,  68, 121,
       101,  56, 141,   6,  80,  36,  72, 113,   4,  89, 127,  94, 138,
        41, 130, 139,  37, 137,   0,  60, 115,  39,  79,  93,  59,  98,
       144,  91,  73,  49, 143,   1,  24])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [15]:
from playML.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [18]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [19]:
from playML.kNN import kNNClassifier

In [23]:
my_knn_clf = kNNClassifier(k=3)

In [24]:
my_knn_clf.fit(X_train, y_train)

kNN(k=3)

In [26]:
y_predict = my_knn_clf.predict(X_test)

In [27]:
y_predict

array([0, 1, 2, 2, 0, 1, 2, 0, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1,
       1, 1, 1, 1, 1, 0, 2, 0])

In [28]:
y_test

array([0, 1, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1,
       1, 1, 1, 1, 1, 0, 2, 0])

In [29]:
sum(y_predict == y_test)

28

In [30]:
 sum(y_predict == y_test) / len(y_test)

0.9333333333333333

## sklearn 中的 train_test_split

In [31]:
 from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [34]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [35]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
