In [32]:
import numpy as np

# 基础
numpy 的主要对象是多维数组，它是一个元素表(通常是数字)，所有元素都具有相同的类型。由非负整数元组索引。在 numpy 中，维度称为轴。

例如:

 [1, 2 ,3]有 1 个轴，该轴有 3 个元素。它的长度为 3。

 [[1, 2, 3],
  [4, ,5 6]] 有 2 个轴。第一个轴的长度为 2(行)，第二个轴的长度为 3(列)。

numpy 的数组称为 ndarray，ndarray对象的重要熟悉有:
* ndarray.ndim 数组的轴数(维度)
* ndarray.shape 数组的维度。对于 n 行 m 列的数组，shape 是(n, m)。shape 元组的长度就是轴数 ndim
* ndarray.size 数组元素的总个数
* ndarray.dtype 数组中元素类型的对象
* ndarray.itemsize 数组中每个元素的大小（以字节为单位）

In [33]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
a.shape

(3, 5)

In [35]:
a.ndim

2

In [36]:
a.dtype.name

'int64'

In [37]:
a.itemsize

8

In [38]:
a.size

15

In [39]:
type(a)

numpy.ndarray

In [40]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [41]:
type(b)

numpy.ndarray

# 数组创建
1. 使用 array 函数从 python 列表或元组创建。
2. 使用 zeros 函数创建一个全 0 的数组。使用 ones 函数创建一个全 1 的函数。使用 empty 函数创建一个初始内容随机的数组。
3. 使用 arange 函数创建数字序列。

In [42]:
a = np.array([1, 2, 3, 4])
# a = np.array(1, 2, 3, 4) 错误写法
a

array([1, 2, 3, 4])

In [43]:
a.dtype

dtype('int64')

In [44]:
b = np.array([1.2, 3.5, 4.7])
b

array([1.2, 3.5, 4.7])

In [45]:
b.dtype

dtype('float64')

In [46]:
np.array([[1, 2, 3], [4, 5 ,6]], dtype=np.float64)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((2, 3, 4), dtype=np.float64)


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
np.empty((2, 3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [52]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

# 基本操作
数组上的算术运算符按照元素进行。创建一个新数组并用结果填充。

算术运算符 * 在 numpy 数组中按照元素进行运算。矩阵乘积使用 @ 运算符或者 dot 函数来执行。

某些操作 *=, += 会就地修改现有数组，而不是创建新数组。

许多一元运算都是作为 ndarray 类的方法实现的。ndarray.sum(), ndarray.min(), ndarray.max()

可以通过 axis 参数，沿数组指定轴应用操作

In [53]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

c = a - b
c

array([20, 29, 38, 47])

In [54]:
b**2

array([0, 1, 4, 9])

In [55]:
a < 35

array([ True,  True, False, False])

In [56]:
a[a < 35]

array([20, 30])

In [57]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

A * B

array([[2, 0],
       [0, 4]])

In [58]:
A @ B

array([[5, 4],
       [3, 4]])

In [59]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [65]:
a = np.empty((2, 3))
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [66]:
a.sum()

21.0

In [67]:
a.max()

6.0

In [68]:
a.min()

1.0

In [69]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [72]:
b.max(axis=1) # max of each row

array([ 3,  7, 11])

# 通用函数

argmin(), argmax() 返回沿轴的最小值/最大值的索引

argsort() 返回对数组进行排序的索引

dot()  2 个数组的点积

mean() 计算沿指定轴的算术平均值。

median() 计算沿指定轴的中位数。


In [79]:
a = np.array([2, 1, 5, 9, 0])
np.argmax(a)

3

In [80]:
np.argmin(a)

4

In [81]:
np.argsort(a)

array([4, 1, 0, 2, 3])

In [82]:
np.mean(a)

3.4

In [83]:
np.median(a)

2.0

# 索引，切片和迭代

一维数组可以别索引，切片和迭代。

多维数组每个轴可以有一个索引，这些索引以逗号分隔的元组出现。当提供的索引数量少于轴的数量时，缺少的索引被视为完整的切片。

如果想对数组中每个元素执行操作，可以使用 flat 属性，它是数组中所有元素的迭代器。

In [84]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [85]:
a[2]

8

In [86]:
a[2:5]

array([ 8, 27, 64])

In [87]:
a[:6:2]

array([ 0,  8, 64])

In [88]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [89]:
a[::-1] #reversed a

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [90]:
b = a.reshape(2, 5)

In [91]:
b

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])

In [92]:
b[0, 1]

1

In [93]:
b[0:2, 0]

array([  0, 125])

In [94]:
b[0:2,:]

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])

In [95]:
b[-1] #相当于 b[-1, :]

array([125, 216, 343, 512, 729])

In [96]:
for elem in b.flat:
    print(elem)

0
1
8
27
64
125
216
343
512
729


# 数组的堆叠与切分

多维数组可以沿着不同的轴堆叠在一起。

对于二维以上的数组， hstack 沿其第二个轴堆叠， vstack 沿其第一个轴堆叠。

np.vstack((a, b))

np.hstack((a, b))

hsplit 沿水平轴分割数组，方法是指定要返回的形状相同的数组的数量，或者指定应在其后进行分割的列。vsplit 沿垂直轴分割。

In [99]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [100]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 副本和视图

1. 根本没有副本：简单的赋值不就复制对象或其数据。python 将可变对象作为引用传递，因此函数调用不会进行复制。
2. 视图或浅拷贝：不同的数组对象可以共享相同的数据。切片数组返回它的视图。
3. 深拷贝：copy 方法创建数组及其数据的完整副本。

In [101]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
b = a # no new object is created
b is a # b and a are two names for the same ndarray object

True

In [102]:
s = a[:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [103]:
s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [104]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [108]:
d = a.copy() # a new array object with new data is created
d

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [109]:
d[:, 1:3] = 20
d

array([[ 0, 20, 20,  3],
       [ 4, 20, 20,  7],
       [ 8, 20, 20, 11]])

In [110]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

## 函数和方法
1. 数组创建：arange, array, cpoy, empty, zeros, linspace
2. 转换：astype
3. 操作：hsplit, hstack, reshape, vsplit, vstack
4. 排序：argmax, argmin, argsort, max, min, sort
5. 基础统计：mean, std
6. 基础线性代数：dot

In [112]:
np.linspace(2.0, 3.0, 5) #返回指定间隔内均匀分布的数字。返回 num 个均匀间隔的样本，在间隔 [start, stop] 上计算。

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [113]:
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [114]:
x.astype(int) #数组的副本，转换为指定类型。

array([1, 2, 2])

## 广播规则
1. 如果所有输入数组的维数不同，则将在较小数组的形状前面重复添加“1”，直到所有数组具有相同的维数。
2. 确保沿特定维度大小为 1 的数组的行为就像它们具有沿该维度具有最大形状的数组的大小一样。假设数组元素的值在“广播”数组的该维度上是相同的。

## 索引
数组可以通过整数数组和布尔值数组进行索引

In [115]:
a = np.arange(12)**2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [116]:
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [117]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [118]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [119]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])