# numpy.array 中的运算

给定一个向量，让向量中的每一个数乘以2

a = (0, 1, 2)

a*2 = (0, 2, 4)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L #将2个L拼接了起来，不是想要的每个元素*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(e * 2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A = []
for e in L:
    A.append(e * 2)

CPU times: user 77.5 ms, sys: 10.5 ms, total: 88.1 ms
Wall time: 89.2 ms


In [6]:
%%time
A = [2*e for e in L]

CPU times: user 45.8 ms, sys: 12.6 ms, total: 58.4 ms
Wall time: 57.4 ms


In [7]:
import numpy as np
L = np.arange(n)

In [11]:
%%time
A = np.array(2*e for e in L)

CPU times: user 56 µs, sys: 883 µs, total: 939 µs
Wall time: 1.92 ms


In [12]:
%%time
A = 2 * L

CPU times: user 4.28 ms, sys: 5.81 ms, total: 10.1 ms
Wall time: 5.98 ms


In [13]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [14]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [15]:
X = np.arange(1, 16).reshape(3, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [17]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [19]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [20]:
X // 2 #整除

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [21]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [22]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [23]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [24]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [26]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [27]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [28]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [29]:
np.power(3, X) # 3**X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [30]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [31]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [32]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [33]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [34]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [35]:
A + B

array([[10, 11],
       [12, 13]])

In [36]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
A * B #对应元素的乘积

array([[ 0, 10],
       [20, 30]])

In [38]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [39]:
A.dot(B) #矩阵真正的乘法

array([[10, 10],
       [50, 50]])

In [40]:
A.T #矩阵的转置

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [41]:
v = np.array([1, 2])

In [42]:
A

array([[0, 1],
       [2, 3]])

In [43]:
v + A #向量和矩阵的每一行做加法

array([[1, 3],
       [3, 5]])

In [44]:
v

array([1, 2])

In [45]:
A

array([[0, 1],
       [2, 3]])

In [46]:
v * A #元素之间的乘法

array([[0, 2],
       [2, 6]])

In [47]:
v.dot(A)

array([4, 7])

In [48]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [49]:
A

array([[0, 1],
       [2, 3]])

In [50]:
np.linalg.inv(A) #A^-1

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [51]:
invA = np.linalg.inv(A)

In [52]:
A.dot(invA) # A*A^-1=单位矩阵

array([[1., 0.],
       [0., 1.]])

In [53]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

## 聚合操作

将一组值变成一个值

In [55]:
L = np.random.random(100)
L

array([0.87950138, 0.82003009, 0.69825431, 0.39781599, 0.64929162,
       0.45798853, 0.97885308, 0.83106571, 0.91141156, 0.27872447,
       0.68991036, 0.03058651, 0.27012597, 0.45851219, 0.23228004,
       0.77939386, 0.22570821, 0.77455438, 0.9529933 , 0.6933676 ,
       0.74527709, 0.42333336, 0.42902051, 0.44775155, 0.04228531,
       0.23349912, 0.79652862, 0.45329331, 0.09515951, 0.18634319,
       0.82306238, 0.09365087, 0.65786789, 0.5819915 , 0.90627285,
       0.32375674, 0.92295775, 0.84125488, 0.23457701, 0.71293631,
       0.56017873, 0.30999984, 0.29752073, 0.74373027, 0.99314298,
       0.21986761, 0.79059349, 0.514771  , 0.94296038, 0.93688617,
       0.81773423, 0.82122913, 0.49994675, 0.35723041, 0.94028825,
       0.78021696, 0.36457194, 0.97238042, 0.58171375, 0.8085981 ,
       0.07048065, 0.39163452, 0.70275383, 0.44626696, 0.29642841,
       0.9752054 , 0.4997533 , 0.74674654, 0.28087037, 0.3640685 ,
       0.83747078, 0.76101144, 0.07678378, 0.11063214, 0.19696

In [56]:
sum(L)

56.20875678971159

In [57]:
np.sum(L)

56.20875678971163

In [58]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

37.7 ms ± 632 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
185 µs ± 1.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [59]:
np.min(big_array)

2.7203494235017445e-08

In [60]:
np.max(big_array)

0.9999983863569758

In [61]:
big_array.min()

2.7203494235017445e-08

In [62]:
big_array.sum()

500256.5140302812

In [63]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.sum(X) #将所有元素聚合

120

In [65]:
np.sum(X, axis=0) #每一列的和，沿着axis方向运算。0代表行。沿着行方向计算结果为列的和

array([24, 28, 32, 36])

In [66]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [67]:
np.prod(X) #返回X中所有元素的乘积

0

In [68]:
np.prod(X + 1)

20922789888000

In [69]:
np.mean(X) #均值

7.5

In [70]:
np.median(X) #中位数

7.5

In [71]:
np.percentile(big_array, q=50) #百分位 50%的元素都小于等于0.5007637279928141

0.5007637279928141

In [72]:
np.percentile(big_array, q=100)

0.9999983863569758

In [73]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, percent))

2.7203494235017445e-08
0.25082566187008765
0.5007637279928141
0.7500369252019456
0.9999983863569758


In [74]:
np.var(big_array) #方差

0.08329019604748025

In [75]:
np.std(big_array) #标准差

0.28860040895237876

## 索引

In [77]:
x = np.random.normal(0, 1, size=1000000)

In [78]:
np.mean(x)

2.580062526715379e-05

In [79]:
np.std(x)

1.0002325283711728

In [80]:
np.min(x)

-4.6905126922686495

In [81]:
np.argmin(x) #返回最小值的索引值

90168

In [82]:
x[90168]

-4.6905126922686495

In [83]:
np.argmax(x)

544638

### 排序和使用索引

In [84]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
np.random.shuffle(x)

In [86]:
x

array([ 5, 12, 10,  3,  8, 11,  4, 14,  9,  0,  6, 15,  2,  1, 13,  7])

In [87]:
np.sort(x) #没有修改x，返回排序好的array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
x.sort() #修改了x
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
X = np.random.randint(10, size=(4, 4))
X

array([[8, 1, 7, 8],
       [1, 4, 6, 3],
       [5, 8, 9, 9],
       [7, 2, 4, 7]])

In [90]:
np.sort(X) #默认将每一行排序

array([[1, 7, 8, 8],
       [1, 3, 4, 6],
       [5, 8, 9, 9],
       [2, 4, 7, 7]])

In [92]:
np.sort(X, axis=0)

array([[1, 1, 4, 3],
       [5, 2, 6, 7],
       [7, 4, 7, 8],
       [8, 8, 9, 9]])

In [93]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
np.random.shuffle(x)
x

array([ 8,  1,  5, 10,  4,  9,  0, 11,  3, 12,  6, 14,  2, 15, 13,  7])

In [96]:
np.argsort(x) #存放的是元素的索引

array([ 6,  1, 12,  8,  4,  2, 10, 15,  0,  5,  3,  7,  9, 14, 11, 13])

In [97]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 12,  9, 14, 10, 15, 13, 11])

In [98]:
np.argpartition(x, 3)

array([ 6,  1, 12,  8,  4,  2, 10, 15,  0,  9,  5, 11,  3, 13, 14,  7])

## Fancy Indexing

In [102]:
x = np.arange(16)
x[3]

3

In [103]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [104]:
x[3:9:2]

array([3, 5, 7])

In [105]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [106]:
ind = [3, 5, 8]

In [107]:
x[ind]

array([3, 5, 8])

In [109]:
ind = np.array([[0, 2],
                [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])